# Generated by Django 3.2.7 on 2021-09-29 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensum', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='program_code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pensum.program'),
        ),
    ]
