# Generated by Django 3.2.7 on 2021-09-29 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('number_semesters', models.SmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Program',
            },
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000, unique=True)),
                ('file_pdf', models.FileField(upload_to='pensum')),
                ('expiration_date', models.DateField()),
                ('date_issue', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('program_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pensum.program')),
            ],
            options={
                'db_table': 'Pensum',
            },
        ),
    ]
