# Generated by Django 3.2.7 on 2021-10-07 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pensum', '0003_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensum',
            name='commission_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pensum.commission'),
            preserve_default=False,
        ),
    ]
