# Generated by Django 3.2.7 on 2021-10-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensum', '0004_pensum_commission_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensum',
            name='file_pdf',
            field=models.FileField(default='pensum/AnalisisdeSistemas.pdf', upload_to='pensum'),
        ),
    ]
